services:
  db:
    image: postgres:latest
    container_name: pocketpartydb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    image: fabioviniciusfsiqueira/pocketparty-backend:latest
    container_name: api-pocketparty
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:senha123@db:5432/devdb?schema=public"
      SECRET: suaChaveSecretaSuperSegura123!@#
      PORT: 3000
      DB_NAME: devdb
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: >
      sh -c "npm run migrate:dev && npm run dev"

volumes:
  postgres_data:
