services:
  db:
    image: postgres:latest
    container_name: pocketpartydb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  authentication:
    image: fabioviniciusfsiqueira/authentication-service:latest
    environment:
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASSWORD: senha123
      DB_HOST: db
      DB_PORT: 5432
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
